import "./globals.css";
import Header from "./header";
import Footer from "./footer";
import { LanguageProvider } from "./context/language-context";// Adjust the import path accordingly

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <LanguageProvider>
          <Header />
          {children}
          <Footer />
        </LanguageProvider>
      </body>
    </html>
  );
}
